challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json
This PR fixes [#17580](https://github.com/freeCodeCamp/freeCodeCamp/issues/17580).
The line `Here's an example of an incomplete sentence.` was unnecessary and was only causing confusion. As discussed in the issue page, I felt that removing the line doesn't make the challenge any less clear but does indeed shortens the length of the challenge text.
If you feel that adding the example was better idea then I will add the example. Please take a look. Thanks.
=> fix: Remove an unnecessary line from basic javascript challenge

challenges/01-responsive-web-design/basic-html-and-html5.json
Closes #18 
@Bouncey 
[https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/nest-an-anchor-element-within-a-paragraph](url)
The link will now open in new tab.
The example and description have been edited to include target attribute.
=> Example link will open in new tab

challenges/02-javascript-algorithms-and-data-structures/es6.json
The regex testing if the user has entered console.log(SENTENCE); has
been modified. In fact, the regex was broken before.
Closes #17679 in freeCodeCamp's main repository
=> fix(challenges): Correct a regex in ES6 read-only challenge

challenges/02-javascript-algorithms-and-data-structures/es6.json
Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/16358
The original test was too rigid, and many users were forced to use one solution, usually map, to
complete the challenge. The test is changed here to allow for multiple solutions to the problem,
including the use of either single or double quotes when naming a class.
Here's a link to regexr with the new regex test and different solutions user's can submit: https://regexr.com/3rdvo
BREAKING CHANGE:
None
=> fix(challenges): change test for template literals challenge

challenges/01-responsive-web-design/applied-visual-design.json
Closes [#15012 in freeCodeCamp repository](https://github.com/freeCodeCamp/freeCodeCamp/issues/15012)
I have already submitted [#17571](https://github.com/freeCodeCamp/freeCodeCamp/pull/17571) pull request in the freeCodeCamp repository for the same issue, all the tests passed successfully, the QA was also complete and it was ready to be merged.
=> updated tests to avoid confusion

challenges/02-javascript-algorithms-and-data-structures/debugging.json
Changes regular expression in testString to remove negative look behind that is not implemented
across all browsers.
ISSUES CLOSED: #55
Targets new `dev` branch of curriculum
Closes #55 
https://github.com/freeCodeCamp/freeCodeCamp/issues/17387
This replicates a PR that was closed on freeCodeCamp (noted in the Issue #55 ) in order to remove a negative look behind used in the regular expression in a test. This is not fully implemented in Firefox yet, but the new expression should take care of the testing as it should.
=> fix(challenges): update regular expression that fails

challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json
removed a test looking for timesFive call and it is not clear from the instrucitons to do so
ISSUES CLOSED: #73
Closes #73
=> fix(challenges): removed a test in basic javascript challenge

challenges/01-responsive-web-design/applied-accessibility.json
BREAKING CHANGE:
none
Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/17729
Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/17723
Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/17623
Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/17577
Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/17477
The assertion for a closing audio tag has 3 conditions that linked by `&&` operators. Two of them always return false, therefore fail the test.
```
// Returns true if the input has a closing tag
code.match(/<\\/audio>/g) 
// Doesn't match anything and returns null
// because the challenge seed
// has an 'id' between 'audio' and 'controls'
code.match(/<audio controls>/g)
// Same as above
code.match(/<\\/audio>/g).length === code.match(/<audio …
```
=> fix(challenges): Applied Accessibility - Improve Accessibility of Audio Content with the audio Element

challenges/02-javascript-algorithms-and-data-structures/es6.json
=> fix(challenges): fixed RegEx for template literals javascript challenge

challenges/01-responsive-web-design/basic-css.json, challenges/01-responsive-web-design/css-flexbox.json
Closes freeCodeCamp/freeCodeCamp#17736
Wrap-reverse definition was incorrectly defined. It has been changed to the correct definition.
=> fix: wrap reverse content

challenges/06-information-security-and-quality-assurance/advanced-express-tools.json
* Write passport.socketio package name properly
* Enhance regexes
* Change error message on failed
attempt to register socket.io middleware
ISSUES CLOSED: #82
In addition to commit message you can check modified logic of new regexes.
https://regexr.com/3rphg
https://regexr.com/3rphm
It works with local development build of freeCodeCamp/learn hosted locally
Closes #82
=> fix(challenges): replace assertions in authentication with socket.io

challenges/01-responsive-web-design/responsive-web-design-projects.json
add user story to center img in parent element. this is part of tests
run on the project but students don't know to implement it until test
fails.
Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/17248
=> fix(challenges): add user story to tribute page challange

challenges/02-javascript-algorithms-and-data-structures/es6.json
I have updated the RegEx for the test cases of [this challenge](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-export-to-reuse-a-code-block). This is related to the [#17771](https://github.com/freeCodeCamp/freeCodeCamp/issues/17771).
This new RegEx makes `space` optional after and before `=` which was the reason for the test failure in [#17771](https://github.com/freeCodeCamp/freeCodeCamp/issues/17771). It also takes care of any number of `space` characters after and before the `=`. 
```js
export const foo="bar"
export const foo = "bar"
export const foo            =          "bar"
```
Above all three cases will pass the test now as they are valid js code.
Please take a look. …
=> fix(challenges): update RegEx for testcase in es6 challenge

challenges/01-responsive-web-design/applied-visual-design.json
Using `s` tag to strikethrough text instead of `del` tag in the applied visual design challenge
ISSUES CLOSED: #17 
Closes #17
=> fix(challenges): change del tag to s tag

challenges/08-coding-interview-prep/data-structures.json
fixed typo in data structures: create and add to sets in ES6
ISSUES CLOSED: freeCodeCamp/freeCodeCamp#17786
Closes freeCodeCamp/freeCodeCamp#17786
=> fix(challenges): fixed a typo in Data structures challege

challenges/01-responsive-web-design/applied-visual-design.json
Fix the regex in use the strong tag to make the text bold in order to only accept Stanford
Yniversity
ISSUES CLOSED: freeCodeCamp/freeCodeCamp#17861
Closes freeCodeCamp/freeCodeCamp#17861
=> fix(challenges): fixed regex in a challenge

challenges/02-javascript-algorithms-and-data-structures/es6.json
Currently, the pre-written code passes the tests which is obviously not acceptable.
This is the challenge with problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/write-concise-declarative-functions-with-es6/
I believe that this is not an optimal fix and can be further improved.
It checks if `: function(anything_here)` **does not exist** in the code or not but if users typed something like this by mistake `function(anything_here)` and submitted the solution then they will pass the challenge with incorrect code.
I think that updating the regex to check if `some_code_here` **exists** in the solution only then the user should pass the test will be better.
If they were done on the …
=> fix(challenges): pre written incorrect code won't pass the test

challenges/01-responsive-web-design/applied-visual-design.json
Updates the regex of the background image challenge to use numeric references that prevent the tests from accepting mismatched quotes. It also allows the user to enter the url without quotes as that is also valid css.
ISSUES CLOSED: #161
=> fix(challenges): fix regex in applied visual design challenge

challenges/01-responsive-web-design/responsive-web-design-projects.json, challenges/03-front-end-libraries/front-end-libraries-projects.json, challenges/04-data-visualization/data-visualization-projects.json
Updated test suite CDN link from:
```
https://gitcdn.link/repo/freeCodeCamp/testable-projects-fcc/master/build/bundle.js
```
to:
```
https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js
```
for projects in these sections: `Responsive Web Design Projects`, `Front End Libraries Projects` and `Data Visualization Projects`.
Context: I believe we decided to host it ourselves because gitcdn kept blacklisting us multiple times. The decision was made but the link in the project description didn't get updated.
Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/17848
Closes …
=> fix(challenges): Update test suite CDN link

challenges/04-data-visualization/json-apis-and-ajax.json
ISSUES CLOSED: freeCodeCamp/freeCodeCamp#17888
Closes freeCodeCamp/freeCodeCamp#17888
=> fix(challenges): change innerHTML to textContent

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Replaces `**` with `####` in issue templates for both feature requests and bug reports. This makes no visual difference, but does make the templates more semantic by causing the markdown-to-html converter to use `<h4>` tags over `<strong>` tags.
Closes #150 
Changes have not been tested locally because the GitHub "pull request" feature cannot be easily emulated online. However, `npm test` has been run and all tests passed.
=> Make issue template headers semantic

challenges/02-javascript-algorithms-and-data-structures/debugging.json
In the objectives, the user was asked to log the variable "outputTwice" whereas in the code editor,
no such variable existed. I changed the objectif so that  it states to change the variable
"outputTwo" which is the variable found in the content.
As Stated above, the variable of the objectives in the challenge "Debugging: Understanding the Differences between the freeCodeCamp and Browser Console" are not the same as the ones in the code editor. I just changed the variable "outputTwice" in the objectives into "outputTwo"
Closes freeCodeCamp/freeCodeCamp#17914
=> fix(challenges): typo in javascript algorithms/debugging/2

challenges/02-javascript-algorithms-and-data-structures/es6.json
Fixes the second test in [Template literals challenge](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/create-strings-using-template-literals/) to allow both single and double quotes around class  - presently only allows double
Relates to #135
=> fix(challenges): allows single quotes

getChallenges.js, schema/challengeSchema.js, unpackedChallenge.js
All fields aren't in the schema will be deleted during repacking. (for example 'hints').
All fields in unpacked HTML will be added in packed JSON.
Formats for Translations and Files have been added in unpacked HTML.
Closes #42
=> fix(scripts): fix unpack and repack scripts for the new challenge schema

challenges/01-responsive-web-design/applied-visual-design.json
Updates the regex of a couple Applied Visual Design challenges that do not allow the user to omit the unit after a zero value.
ISSUES CLOSED: #166
=> fix(challenges): allow for omitted unit after zero values

docs/CONTRIBUTING.md
Specifies that a pull request will fail the Travis CI build without conventional commit messages and
adds a link with more info about conventional commits.
Closes #XXXXX
=> docs(contributing): add info on conventional commit messages

challenges/02-javascript-algorithms-and-data-structures/basic-data-structures.json
Fixing typo in algorithms and data structures lesson having to do with combining arrays with the spread operator. Deleted the multiple word 'more'.
Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/18003
=> Typo in Basic Data Structures: Combine Arrays with the Spread Operator #18003 FIX

challenges/02-javascript-algorithms-and-data-structures/regular-expressions.json
There was no test to make sure inputs with only one digit would fail. I added the test and then added a solution as well.
ISSUES CLOSED: #209
=> fix(challenges): add test to lookahead regex challenge

challenges/02-javascript-algorithms-and-data-structures/es6.json
ISSUES CLOSED: #213
I updated [ES6: Use Destructuring Assignment to Assign Variables from Objects](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-to-assign-variables-from-objects/) so that it no longer requires the user to understand the difference between string primitives and string objects. It now follows the same theme as the challenge that follows.
This is the new `contents` of the challenge:
```javascript
const AVG_TEMPERATURES = {
today: 77.5,
tomorrow: 79
};
function getTempOfTmrw(avgTemperatures) {
"use strict";
// change code below this line
const tempOfTomorrow = undefined; // change this line
// change code above this line
return tempOfTomorrow;
}
console.log(getTempOfTmrw(AVG_TEMPERATURES)); // should be 79
```
And …
=> fix(challenges): fix confusing destructuring es6 challenge

challenges/01-responsive-web-design/basic-html-and-html5.json
This code converts the tests of the Delete HTML Elements challenge to use regex instead of jQuery. This prevents some weird behavior as shown below. This change also makes it possible to add a solution to be tested with the test suite so I included that as well.
The following code currently passes, but it will not pass with this change:
```html
Hello World</h1>
<h2>
<p>
```
My actual changes start on line 568 and go through 587.
Closes #251
=> fix(challenges): converts delete html tests to regex

challenges/01-responsive-web-design/css-flexbox.json
ISSUES CLOSED: #260
I improved regex for this challenge a little bit by ensuring the flex-direction declarations are in the right rules while also removing the line number restriction. 
I also thought about using jQuery in the tests, but that is not possible here because row is already the default value of `flex-direction`, so you could pass the challenge without doing anything.
Closes #260
=> fix(challenges): fix flex direction row regex

challenges/01-responsive-web-design/responsive-web-design.json
ISSUES CLOSED: #271
Updated the regex for the second test to include white spaces between brackets and the text inside.
Closes #271
=> fix(challenges): Update test to include whitespace

challenges/01-responsive-web-design/basic-css.json
I fixed the description in this [challenge](https://learn.freecodecamp.org/responsive-web-design/basic-css/attach-a-fallback-value-to-a-css-variable/) to point out that the variable fallback is not used to work with browsers that don't support variables.
I also updated the instruction to call out exactly what is going on rather than explaining it as a note at the bottom.
PARTIALLY RESOLVES: freeCodeCamp/freeCodeCamp#17546
=> fix(challenges): fix description in css variable fallback challenge

challenges/03-front-end-libraries/react.json
Previously it was possible for the tests to fail if the timeout in componentDidMount() was too small - less than approximately 500ms.  This change sets the state and checks that the component has been correctly rendered synchronously.  As a result the timeout can be changed without issue.
Closes freeCodeCamp/freeCodeCamp#17988
=> fix(challenges): remove race condition from react lifecycle challenge

challenges/02-javascript-algorithms-and-data-structures/es6.json
The challenge ES6: Use Destructuring Assignment with the Rest Operator to Reassign Array Elements, had slightly odd test descriptions and the tests didn't quite capture what they should.  For example, if the user did not use a destructuring operator they'd be told 'destructuring was used.'.  Also, the tests passed and failed some things they shouldn't.  As mentioned in #281, returning an empty array would pass the first test.  The second test required the use of the variable `arr`, which is not strictly necessary.  Finally the third test would only fail if it found 'Array.slice' in the editor, but would pass `let arr = list.slice(2)`.
This PR addresses those issue by slightly tweaking the text and tightening/relaxing the tests, as appropriate.
Learn more here: …
=> fix(challenges): reword test text and improve test accuracy

challenges/01-responsive-web-design/css-flexbox.json
Fix typo in wrap-reverse description. (see #287)
Change description of `wrap-reverse` from
- "wraps items from bottom-to-top if they are in a row, or **left-to-right** if they are in a column", to
- "wraps items from bottom-to-top if they are in a row, or **right-to-left** if they are in a column".
_Note: I haven't set up the entire testing environment for such a tiny typo, so the testing wasn't done locally._ 
Closes #287
=> fix(challenges): Fix typo in wrap-reverse description

challenges/01-responsive-web-design/basic-html-and-html5.json
should have said elements and not tags
=> fix(challenges): small edit to correct semantic issues

challenges/02-javascript-algorithms-and-data-structures/debugging.json
This PR adds solutions to the first three js debugging challenges. It is related to #250. As I have time will will submit more PRs to get the rest of the solutions in there.
=> fix(challenges): add solutions to first 3 debugging challenges

challenges/06-information-security-and-quality-assurance/helmetjs.json
frames and other code in description were not surrounded by `<code>` tags and rendering poorly on
page.
ISSUES CLOSED: #17911-freecodecamp
https://github.com/freeCodeCamp/freeCodeCamp/issues/17911
Closes #17911
https://github.com/freeCodeCamp/freeCodeCamp/issues/17911
=> fix(challenges): adding code tags to description

challenges/03-front-end-libraries/jquery.json, challenges/04-data-visualization/data-visualization-with-d3.json, challenges/04-data-visualization/json-apis-and-ajax.json
This changes the `challengeType` of some challenges so that their 'Ask for help' buttons redirect to the correct sub-forum, as discussed in freecodecamp/learn#259.  In isolation, this doesn't fix that issue, but it is part of the solution.
Closes #XXXXX
=> fix(challenges): change challengeType to fix help button
