- challenges/08-coding-interview-prep/rosetta-code.json
Update ID of "I before E except after C" Rosetta problem
Closes #XXXXX
> Update ID of "I before E except after C"

- challenges/09-certificates/responsive-web-design-certificate.json
BREAKING CHANGE:
none
Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/17698
Fixed the issue with claiming the Responsive Web Design Certification by giving the 'Build a Personal Portfolio Webpage' project the correct id.
This one was actually fixed twice (https://github.com/freeCodeCamp/freeCodeCamp/pull/17389 and https://github.com/freeCodeCamp/freeCodeCamp/pull/17102), but I don't know why it's still not reflected here. Maybe there is some issue with the recent migration?
Feel free to close my PR if you can somehow rollback/apply the old fixes.
> fix(challenges): fix responsive web design cert claim

- challenges/01-responsive-web-design/css-grid.json
Closes [#17711](https://github.com/freeCodeCamp/freeCodeCamp/issues/17711)
Changed `propertiy` to `property` in `challenges/01-responsive-web-design/css-grid.json`.
Just fixing a small typo as my first contribution.
> fix(challenges): fixed typo in css-grid.json

- challenges/01-responsive-web-design/css-grid.json
Closes [freeCodeCamp/#17691](https://github.com/freeCodeCamp/freeCodeCamp/issues/17691)
Add -ly suffix to "identical" in first line of CSS Grid auto-fit challenge
*Note:* reposts [this previously closed fix](https://github.com/freeCodeCamp/freeCodeCamp/pull/17692#issuecomment-400081302) to the `curriculum` repository.
> fix(challenges): grammar fix in css-grid auto-fit challenge

- challenges/01-responsive-web-design/basic-css.json
- challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json
- challenges/03-front-end-libraries/react.json
Closes [freeCodeCamp/#17697](https://github.com/freeCodeCamp/freeCodeCamp/issues/17697),
[freeCodecamp/#17699](https://github.com/freeCodeCamp/freeCodeCamp/issues/17699), 
[freeCodeCamp/#17654](https://github.com/freeCodeCamp/freeCodeCamp/issues/17654),
[freeCodeCamp/#17685](https://github.com/freeCodeCamp/freeCodeCamp/issues/17685),
[freeCodeCamp/#17725](https://github.com/freeCodeCamp/freeCodeCamp/issues/17725),
[freeCodeCamp/#17721](https://github.com/freeCodeCamp/freeCodeCamp/issues/17721)
Fixed Typos.
> Typo errors

- challenges/05-apis-and-microservices/managing-packages-with-npm.json
- [* ] Your pull request targets the `staging` branch of freeCodeCamp.
- [* ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ *] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [* ] Small bug fix (non-breaking change which fixes an issue)
Closes #XXXXX
I noticed that there was a comment ('TODO: This challenge could be used to inspire more people to develop OSS - we should really improve this description.') in HTML on this page (it was not commented out):
https://learn.freecodecamp.org/apis-and-microservices/managing-packages-with-npm/add-a-license-to-your-package-json
This is my first Pull Request and believe I have targeted the problem …
> fix(challenges): removed comment in the seed

- challenges/01-responsive-web-design/css-flexbox.json
Closes [#17724](https://github.com/freeCodeCamp/freeCodeCamp/issues/17724)
As mentioned in [#17724](https://github.com/freeCodeCamp/freeCodeCamp/issues/17724), setting `align-items: center` to the header elements `h3` and `h4` doesn't make any sense. In fact, it's incorrect to do so because `align-items` property should be applied to containers.
Please take a look at this and suggest for any change if required.
Cheers!
> fix(challenges): remove unnecessary test cases

- challenges/03-front-end-libraries/bootstrap.json
> fix(challenges): removed redundant text from challenge

- CHANGELOG.md
- package-lock.json
- package.json
* **challenges:** change comment to make it clearer ([#72](https://github.com/freeCodeCamp/curriculum/issues/72)) ([46fcf43](https://github.com/freeCodeCamp/curriculum/commit/46fcf43))
* **challenges:** fix a test case in an Applied Accessibility ([4c0d587](https://github.com/freeCodeCamp/curriculum/commit/4c0d587))
* **challenges:** remove unnecessary test cases ([17af3dd](https://github.com/freeCodeCamp/curriculum/commit/17af3dd))
* **challenges:** removed a test in basic javascript challenge ([#76](https://github.com/freeCodeCamp/curriculum/issues/76)) ([ff26697](https://github.com/freeCodeCamp/curriculum/commit/ff26697)), closes [#73](https://github.com/freeCodeCamp/curriculum/issues/73)
* **challenges:** removed comment in the seed …
> chore(release): 3.0.1 [skip ci]

- challenges/01-responsive-web-design/responsive-web-design-projects.json
Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/17624
Helped to clarify the instructions by letting users know the number range is defined by their min and max attributes.
> fix: clarify unclear instructions

- challenges/03-front-end-libraries/sass.json
Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/17626
> fix: incomplete Sass Test

- .gitignore
> fix(gitignore file): added .vscode and unpacked folder to the file

- challenges/06-information-security-and-quality-assurance/advanced-express-tools.json
add a comma and fix an awkward sentence
I fixed two typos in the challenge description. 
1. I added a comma in list item 2 after passport.authenticate('github'). 
Previous text:
Your route calls passport.authenticate('github') which redirects them to Github.
My change: 
Your route calls passport.authenticate('github'), which redirects them to Github.
2. I changed list item 3 as there was one long, awkward sentence.  I made it 2 sentences. 
Previous text:
The page the user lands on, on Github, allows them to login if they aren't already then asks them to approve access to their profile from our app.
My change: 
The page the user lands on, on Github, allows them to login if they aren't already. It then asks them to approve access to their profile from our app.
Learn more here: …
> fix(challenges): fix typos

- .gitignore
added the dist/ folder to the list, this directory is formed after running npm run build
Missed the dist/ folder in my last commit
> fix(.gitignore file): added dist/ folder

- challenges/01-responsive-web-design/css-grid.json
- challenges/02-javascript-algorithms-and-data-structures/es6.json
- challenges/08-coding-interview-prep/rosetta-code.json
- challenges/09-certificates/responsive-web-design-certificate.json
> Porting Rosetta problems

- challenges/05-apis-and-microservices/apis-and-microservices-projects.json
The microservices challenges test suite is empty. I added 5 tests for the microservice api
partially address [#17131](https://github.com/freeCodeCamp/freeCodeCamp/issues/17131)
> feat(challenge): add tests for the timestamp microservice challenge

- challenges/06-information-security-and-quality-assurance/advanced-express-tools.json
ISSUES CLOSED: #17769, #17039, #16967
Replaced regex /Home page/gi with /Looks like this page is being rendered from Pug into HTML!/gi in order to fix the bug and make the test pass.
Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/17769
Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/17039
Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/16967
The above issues were opened in freeCodeCamp repo
> fix(challenges): fix 2nd test bug

- challenges/01-responsive-web-design/applied-visual-design.json
Changed `:before` and `:after` to `::before` and `::after` respectively. Fixes #14 
Closes #14
> fix(challenges): update pseudo-element selector syntax from CSS2 to CSS3

- challenges/08-coding-interview-prep/project-euler.json
@scissorsneedfoodtoo 
Edited description and added solution for Project Euler problem 52
Here's the solution
```javascript
function permutedMultiples() {
const isPermutation = (a, b) => 
a.length !== b.length 
? false
: a.split('').sort().join() === b.split('').sort().join();
let start = 1;
let found = false;
let result = 0;
while (!found) {
start *= 10;
for (let i = start; i < start * 10 / 6; i++) {
found = true;
for (let j = 2; j <= 6; j++) {
if (!isPermutation(i + '', j * i + '')) {
found = false;
break;
}
}
if (found) {
result = i;
break;
}
}
}
return result;
}
```
Closes #XXXXX
> fix(challenges): add solution and edited description for project euler 52

- challenges/08-coding-interview-prep/data-structures.json
fixed: unable solve challenges without editing code outside comments
Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/17675
> fix(challenges): fix initial contents

- challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json
ISSUES CLOSED: [#freeCodeCamp/17823](https://github.com/freeCodeCamp/freeCodeCamp/issues/17823)
Fixed a broken link.
> fix(challenges): broken link

- challenges/01-responsive-web-design/basic-css.json
Fix a test case typo so it does not confuse the student on what needs to be done. 
Closes #116 
> fix(challenge): typos in first Basic CSS challenge test

- challenges/01-responsive-web-design/basic-css.json
The variable name needs to be incorrect so that the fallback value is used.
Closes [freeCodeCamp/#17840](https://github.com/freeCodeCamp/freeCodeCamp/issues/17840),
Closes [freeCodeCamp/#17699](https://github.com/freeCodeCamp/freeCodeCamp/issues/17699),
> fix(challenges): fix challenge for fallback value of CSS variable

- challenges/05-apis-and-microservices/mongodb-and-mongoose.json
> fix(challenges): fix typo in findOneAndUpdate() challenge

- .gitignore
- challenges/01-responsive-web-design/css-grid.json
> Fix css-grid.json typo

- challenges/02-javascript-algorithms-and-data-structures/es6.json
The variable name needs to be incorrect so that fallback value is applied.
Closes [freeCodeCamp/#17845](https://github.com/freeCodeCamp/freeCodeCamp/issues/17845)
> fix(challenges): fix regex to allow redundant space characters

- challenges/08-coding-interview-prep/project-euler.json
Added solution and put more assertions for project euler 53
Here's the solution
```javascript
function combinatoricSelections(max) {
const factorial = n => 
Array.apply(null, { length: n })
.map((_, i) => i + 1)
.reduce((p, c) => p * c, 1);
let result = 0;
const nMax = 100;
for (let n = 1; n <= nMax; n++) {
for (let r = 0; r <= n; r++) {
if (factorial(n) / (factorial(r) * factorial(n - r)) >= max)
result++;
}
}
return result;
}
```
Closes #XXXXX
> fix(challenges): add solution to project euler 53

- challenges/05-apis-and-microservices/basic-node-and-express.json
I fixed a small typo in the 'Basic Node and Express - Start a Working Express Server' challenge (environemet -> environment).
I ran 'npm run test' locally and passed all tests.
Closes #XXXXX
> fix(challenges): fix typo in node and express challenge

- challenges/04-data-visualization/data-visualization-with-d3.json
Incorrect spelling of values(was vales).
Closes [freeCodeCamp/#17875](https://github.com/freeCodeCamp/freeCodeCamp/issues/17875)
> fix(challenges): typo error

- challenges/03-front-end-libraries/redux.json
> fix(challenges): remove obsolete mention of beta and update link

- challenges/02-javascript-algorithms-and-data-structures/es6.json
Made several changes to the lesson to give a better intro to template literals and correct a couple of minor errors.
Closes #XXXXX
> Improve template literals lesson

- challenges/02-javascript-algorithms-and-data-structures/functional-programming.json
```
var otherString = "How9are7you2today";
var byDigits = str.split(/\d/);
// Sets byDigits to ["How", "are", "you", "today"]
```
It should be `var byDigits = **otherString**.split(/\d/);`
Closes [freeCodeCamp/#17880](https://github.com/freeCodeCamp/freeCodeCamp/issues/17880)
> fix(challenges): fix typo in "split string into array using split"

- challenges/01-responsive-web-design/basic-html-and-html5.json
- challenges/05-apis-and-microservices/mongodb-and-mongoose.json
Fixed grammatical error in challenge basic-html/uncomment.
Closes:
[freeCodeCamp/#17900](https://github.com/freeCodeCamp/freeCodeCamp/issues/17900)
[freeCodeCamp/#17904](https://github.com/freeCodeCamp/freeCodeCamp/issues/17904)
> fix(challenges): grammatical error

- challenges/01-responsive-web-design/responsive-web-design-projects.json
- challenges/03-front-end-libraries/front-end-libraries-projects.json
- challenges/04-data-visualization/data-visualization-projects.json
Hi guys 👋 
For some challenges, I found that the URL for FCC's test bundle is not valid (404).
Updated the old test bundle URL with the new one. I think this issue was not reported, I simply stumbled upon it.
Closes #XXXXX
> fix(challenges): fix broken test bundle url

- challenges/01-responsive-web-design/basic-css.json
ISSUES CLOSED: #169
Made green-box margins match red-box margins. There is no need for a difference in margins for this challenge. This change also makes it more visually appealing since siblings match in size.
Closes #169
> fix(challenges): change green-box class margin to match red-box

- challenges/05-apis-and-microservices/mongodb-and-mongoose.json
Added the word "multiple" to the description of the "Use model.findOne() to Return a Single Matching
Document from Your Database" challenge.
Closes #XXXXX
> fix(challenges): fix typo in a "mongodb and mongoose" challenge

- challenges/02-javascript-algorithms-and-data-structures/es6.json
The user was able to pass the challenge without building a proper constructor for the class. The new
objective ensure a constructor was built.
As stated above in the 19th ES6 challenge, the user was able to pass the challenge without having to build a proper constructor. Simply creating a class named vegetable was sufficient to pass the challenge, even if it was asked in the instructions to create a constructor.
I added an objectif so the presence of a constructor for the class "Vegetable" is checked by asserting the value "name" of "carrot" which is an instance of the "Vegetable" class and that was already present in the user's code editor.  
link to the challenge : https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-class-syntax-to-define-a-constructor-functi …
> fix(challenges): insufficient objectives for javascript_algorithm/es6/19

- challenges/08-coding-interview-prep/data-structures.json
ISSUES CLOSED: #164
I added the solutions for «Data Structures: Add a New Element to a Binary Search Tree» challenge and I also modified one test to fix issue #164
Closes #164
> fix(challenges): update test and add solution for DS challenge

- challenges/08-coding-interview-prep/data-structures.json
ISSUES CLOSED: #193
Provided a clear and concise description for ‘has’ method in Create a Map Data Structure Challenge and also listed the instructions for the challenge into a bullet list.
Sorry for typo in commit message.
Closes #193
> fix(challenges): challenge description is formatted and concised

- challenges/01-responsive-web-design/css-grid.json
ISSUES CLOSED: #229
This updates the regex to use a `+` instead of a `*` between the two measurements so that it requires at least one space.
Closes #229
> fix(challenges): fix grid-gap shorthand regex

- challenges/08-coding-interview-prep/rosetta-code.json
> feat(interview-prep): Porting Rosetta problems

- challenges/02-javascript-algorithms-and-data-structures/regular-expressions.json
Added a test to check if the user is using the \W character. This will prevent them passing by using ^\w
Closes #218
> fix(challenges): add test to check user is using \W in Regex

- challenges/01-responsive-web-design/basic-html-and-html5.json
Incorrect html closing tag in code displayed in editor.
Closes [freeCodeCamp#18018](
https://github.com/freeCodeCamp/freeCodeCamp/issues/18018)
> fix(challenges): Incorrect html closing tag

- challenges/01-responsive-web-design/applied-visual-design.json
In order to clarify the meaning in the second paragraph of the challenge, the text has been changed to say:
> One key difference between the fixed and absolute positions is that an element with a fixed position won't move when the user scrolls.
Closes #18043
> fix(challenges): rephrased wording in applied visual design

- challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json
Hi @QuincyLarson !
I've added a test for if else statements curly braces to ensure that every condition has to have
both opening and closing curly braces.
ISSUES CLOSED: #17155
I've added additional test case to Basic JavaScript: Introducing Else if statements challenge to ensure that every condition in in the else if statement has to have both opening and closing curly braces.
https://github.com/freeCodeCamp/freeCodeCamp/issues/17155
Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/17155
> fix(challenges): fix regex in introducing else if challenge

- challenges/02-javascript-algorithms-and-data-structures/es6.json
In the ES6 challenge - [Use Arrow Functions to Write Concise Anonymous Functions](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-arrow-functions-to-write-concise-anonymous-functions/) the code example for arrow function was:
```
const myFunc= () => "value"
```
There is a space missing after myFunc and it has been changed to:
```
const myFunc = () => "value"
```
Closes #XXXXX
> fix(challenges): missing space in code example

- challenges/01-responsive-web-design/basic-css.json
This is what I came up with for a browser fallback challenge. It's not perfect, but I think it gets the job done. I am open to making updates so your feedback is appreciated.
Closes freeCodeCamp/freeCodeCamp#17546
> feat(challenges): add browser fallback challenge

- challenges/01-responsive-web-design/applied-visual-design.json
There were two duplicate css top properties. As suggested, I removed the one with a fixed top setting.
Closes #205
> fix(challenges): removed duplicate css top property applied visual design

- challenges/04-data-visualization/data-visualization-with-d3.json
Add a short message in note at bottom of description in d3 challenge
ISSUES CLOSED: https://github.com/freeCodeCamp/freeCodeCamp/issues/17767
Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/17767
> fix(challenges): add note at bottom of description in d3 challenge

- challenges/02-javascript-algorithms-and-data-structures/debugging.json
ISSUES CLOSED: #18046
Reworded information because it didn't make sense beforehand. 
Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/18046
> fix(challenges): a sentence didn't make sense, so I modified it

- challenges/08-coding-interview-prep/project-euler.json
This commit adds solutions to project Euler problems 28 and 31.
Closes #XXXXX
> fix(challenges): added solutions to project euler problems 28, 31

- challenges/02-javascript-algorithms-and-data-structures/debugging.json
ISSUES CLOSED: #17947
Closes #17947
> docs(tools): fixed a typo in the challenge "you" => "your"
